/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const FarmerId = IDL.Nat;
export const Farmer = IDL.Record({
  'id' : FarmerId,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'address' : IDL.Text,
  'village' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const FarmerError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'notFound' : FarmerId,
  'duplicateCode' : IDL.Text,
});
export const Kg = IDL.Nat;
export const DateText = IDL.Text;
export const Money = IDL.Nat;
export const Product = IDL.Variant({
  'mustard' : IDL.Null,
  'other' : IDL.Null,
  'pear' : IDL.Null,
  'banana' : IDL.Null,
  'passion' : IDL.Null,
  'woodApple' : IDL.Null,
  'guava' : IDL.Null,
});
export const HarvestInput = IDL.Record({
  'kg' : Kg,
  'farmerId' : FarmerId,
  'date' : DateText,
  'pricePerKg' : Money,
  'product' : Product,
});
export const HarvestId = IDL.Nat;
export const OfficerId = IDL.Nat;
export const Harvest = IDL.Record({
  'id' : HarvestId,
  'kg' : Kg,
  'officerId' : OfficerId,
  'total' : Money,
  'farmerId' : FarmerId,
  'date' : DateText,
  'createdAt' : IDL.Int,
  'officerName' : IDL.Text,
  'pricePerKg' : Money,
  'farmerCode' : IDL.Text,
  'farmerName' : IDL.Text,
  'product' : Product,
});
export const HarvestError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'farmerNotFound' : FarmerId,
  'notFound' : HarvestId,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Role = IDL.Variant({ 'admin' : IDL.Null, 'officer' : IDL.Null });
export const Session = IDL.Record({
  'id' : OfficerId,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'role' : Role,
});
export const AuthError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'lastAdmin' : IDL.Null,
  'notFound' : IDL.Null,
  'invalidCredentials' : IDL.Null,
  'usernameTaken' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const DashboardStats = IDL.Record({
  'totalValue' : Money,
  'date' : DateText,
  'totalKg' : Kg,
  'farmerCount' : IDL.Nat,
  'recordCount' : IDL.Nat,
});
export const HarvestSummary = IDL.Record({
  'id' : HarvestId,
  'kg' : Kg,
  'officerId' : OfficerId,
  'total' : Money,
  'date' : DateText,
  'officerName' : IDL.Text,
  'pricePerKg' : Money,
  'product' : Product,
});
export const Dashboard = IDL.Record({
  'stats' : DashboardStats,
  'recent' : IDL.Vec(HarvestSummary),
});
export const FarmerDetail = IDL.Record({
  'harvests' : IDL.Vec(HarvestSummary),
  'farmer' : Farmer,
});
export const ReportKind = IDL.Variant({
  'byOfficer' : IDL.Null,
  'byProduct' : IDL.Null,
  'byFarmer' : IDL.Null,
  'monthly' : IDL.Null,
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const ReportRow = IDL.Record({
  'kg' : Kg,
  'key' : IDL.Text,
  'title' : IDL.Text,
  'value' : Money,
  'count' : IDL.Nat,
});
export const Report = IDL.Record({
  'to' : DateText,
  'totalValue' : Money,
  'from' : DateText,
  'totalKg' : Kg,
  'kind' : ReportKind,
  'rows' : IDL.Vec(ReportRow),
  'recordCount' : IDL.Nat,
});
export const ReportError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'invalidRange' : IDL.Null,
});
export const CredentialRow = IDL.Record({
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'password' : IDL.Text,
  'role' : Role,
});
export const PriceEntry = IDL.Record({
  'pricePerKg' : Money,
  'updatedAt' : IDL.Int,
  'product' : Product,
});
export const PriceError = IDL.Variant({ 'notAuthorized' : IDL.Null });

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addFarmer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Farmer, 'err' : FarmerError })],
      [],
    ),
  'addHarvest' : IDL.Func(
      [HarvestInput],
      [IDL.Variant({ 'ok' : Harvest, 'err' : HarvestError })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOfficer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Session, 'err' : AuthError })],
      [],
    ),
  'deleteHarvest' : IDL.Func(
      [HarvestId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : HarvestError })],
      [],
    ),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboard' : IDL.Func([DateText], [Dashboard], ['query']),
  'getFarmer' : IDL.Func([FarmerId], [IDL.Opt(FarmerDetail)], ['query']),
  'getFarmerHarvests' : IDL.Func(
      [FarmerId],
      [IDL.Vec(HarvestSummary)],
      ['query'],
    ),
  'getHarvest' : IDL.Func([HarvestId], [IDL.Opt(Harvest)], ['query']),
  'getReport' : IDL.Func(
      [ReportKind, DateText, DateText],
      [IDL.Variant({ 'ok' : Report, 'err' : ReportError })],
      ['query'],
    ),
  'getSeededCredentials' : IDL.Func([], [IDL.Vec(CredentialRow)], ['query']),
  'getSession' : IDL.Func([], [IDL.Opt(Session)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listFarmers' : IDL.Func([], [IDL.Vec(Farmer)], ['query']),
  'listHarvests' : IDL.Func([], [IDL.Vec(Harvest)], ['query']),
  'listOfficers' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'listPrices' : IDL.Func([], [IDL.Vec(PriceEntry)], ['query']),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text, Role],
      [IDL.Variant({ 'ok' : Session, 'err' : AuthError })],
      [],
    ),
  'logout' : IDL.Func([], [], []),
  'resetOfficerPassword' : IDL.Func(
      [OfficerId, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError })],
      [],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchFarmers' : IDL.Func([IDL.Text], [IDL.Vec(Farmer)], ['query']),
  'setPrice' : IDL.Func(
      [Product, Money],
      [IDL.Variant({ 'ok' : PriceEntry, 'err' : PriceError })],
      [],
    ),
  'updateFarmer' : IDL.Func(
      [FarmerId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Farmer, 'err' : FarmerError })],
      [],
    ),
  'updateHarvest' : IDL.Func(
      [HarvestId, HarvestInput],
      [IDL.Variant({ 'ok' : Harvest, 'err' : HarvestError })],
      [],
    ),
  'updateOfficer' : IDL.Func(
      [OfficerId, IDL.Text],
      [IDL.Variant({ 'ok' : Session, 'err' : AuthError })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const FarmerId = IDL.Nat;
  const Farmer = IDL.Record({
    'id' : FarmerId,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'address' : IDL.Text,
    'village' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const FarmerError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'notFound' : FarmerId,
    'duplicateCode' : IDL.Text,
  });
  const Kg = IDL.Nat;
  const DateText = IDL.Text;
  const Money = IDL.Nat;
  const Product = IDL.Variant({
    'mustard' : IDL.Null,
    'other' : IDL.Null,
    'pear' : IDL.Null,
    'banana' : IDL.Null,
    'passion' : IDL.Null,
    'woodApple' : IDL.Null,
    'guava' : IDL.Null,
  });
  const HarvestInput = IDL.Record({
    'kg' : Kg,
    'farmerId' : FarmerId,
    'date' : DateText,
    'pricePerKg' : Money,
    'product' : Product,
  });
  const HarvestId = IDL.Nat;
  const OfficerId = IDL.Nat;
  const Harvest = IDL.Record({
    'id' : HarvestId,
    'kg' : Kg,
    'officerId' : OfficerId,
    'total' : Money,
    'farmerId' : FarmerId,
    'date' : DateText,
    'createdAt' : IDL.Int,
    'officerName' : IDL.Text,
    'pricePerKg' : Money,
    'farmerCode' : IDL.Text,
    'farmerName' : IDL.Text,
    'product' : Product,
  });
  const HarvestError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'farmerNotFound' : FarmerId,
    'notFound' : HarvestId,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Role = IDL.Variant({ 'admin' : IDL.Null, 'officer' : IDL.Null });
  const Session = IDL.Record({
    'id' : OfficerId,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'role' : Role,
  });
  const AuthError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'lastAdmin' : IDL.Null,
    'notFound' : IDL.Null,
    'invalidCredentials' : IDL.Null,
    'usernameTaken' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const DashboardStats = IDL.Record({
    'totalValue' : Money,
    'date' : DateText,
    'totalKg' : Kg,
    'farmerCount' : IDL.Nat,
    'recordCount' : IDL.Nat,
  });
  const HarvestSummary = IDL.Record({
    'id' : HarvestId,
    'kg' : Kg,
    'officerId' : OfficerId,
    'total' : Money,
    'date' : DateText,
    'officerName' : IDL.Text,
    'pricePerKg' : Money,
    'product' : Product,
  });
  const Dashboard = IDL.Record({
    'stats' : DashboardStats,
    'recent' : IDL.Vec(HarvestSummary),
  });
  const FarmerDetail = IDL.Record({
    'harvests' : IDL.Vec(HarvestSummary),
    'farmer' : Farmer,
  });
  const ReportKind = IDL.Variant({
    'byOfficer' : IDL.Null,
    'byProduct' : IDL.Null,
    'byFarmer' : IDL.Null,
    'monthly' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const ReportRow = IDL.Record({
    'kg' : Kg,
    'key' : IDL.Text,
    'title' : IDL.Text,
    'value' : Money,
    'count' : IDL.Nat,
  });
  const Report = IDL.Record({
    'to' : DateText,
    'totalValue' : Money,
    'from' : DateText,
    'totalKg' : Kg,
    'kind' : ReportKind,
    'rows' : IDL.Vec(ReportRow),
    'recordCount' : IDL.Nat,
  });
  const ReportError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'invalidRange' : IDL.Null,
  });
  const CredentialRow = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'password' : IDL.Text,
    'role' : Role,
  });
  const PriceEntry = IDL.Record({
    'pricePerKg' : Money,
    'updatedAt' : IDL.Int,
    'product' : Product,
  });
  const PriceError = IDL.Variant({ 'notAuthorized' : IDL.Null });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addFarmer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Farmer, 'err' : FarmerError })],
        [],
      ),
    'addHarvest' : IDL.Func(
        [HarvestInput],
        [IDL.Variant({ 'ok' : Harvest, 'err' : HarvestError })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOfficer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Session, 'err' : AuthError })],
        [],
      ),
    'deleteHarvest' : IDL.Func(
        [HarvestId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : HarvestError })],
        [],
      ),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboard' : IDL.Func([DateText], [Dashboard], ['query']),
    'getFarmer' : IDL.Func([FarmerId], [IDL.Opt(FarmerDetail)], ['query']),
    'getFarmerHarvests' : IDL.Func(
        [FarmerId],
        [IDL.Vec(HarvestSummary)],
        ['query'],
      ),
    'getHarvest' : IDL.Func([HarvestId], [IDL.Opt(Harvest)], ['query']),
    'getReport' : IDL.Func(
        [ReportKind, DateText, DateText],
        [IDL.Variant({ 'ok' : Report, 'err' : ReportError })],
        ['query'],
      ),
    'getSeededCredentials' : IDL.Func([], [IDL.Vec(CredentialRow)], ['query']),
    'getSession' : IDL.Func([], [IDL.Opt(Session)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listFarmers' : IDL.Func([], [IDL.Vec(Farmer)], ['query']),
    'listHarvests' : IDL.Func([], [IDL.Vec(Harvest)], ['query']),
    'listOfficers' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'listPrices' : IDL.Func([], [IDL.Vec(PriceEntry)], ['query']),
    'login' : IDL.Func(
        [IDL.Text, IDL.Text, Role],
        [IDL.Variant({ 'ok' : Session, 'err' : AuthError })],
        [],
      ),
    'logout' : IDL.Func([], [], []),
    'resetOfficerPassword' : IDL.Func(
        [OfficerId, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError })],
        [],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchFarmers' : IDL.Func([IDL.Text], [IDL.Vec(Farmer)], ['query']),
    'setPrice' : IDL.Func(
        [Product, Money],
        [IDL.Variant({ 'ok' : PriceEntry, 'err' : PriceError })],
        [],
      ),
    'updateFarmer' : IDL.Func(
        [FarmerId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Farmer, 'err' : FarmerError })],
        [],
      ),
    'updateHarvest' : IDL.Func(
        [HarvestId, HarvestInput],
        [IDL.Variant({ 'ok' : Harvest, 'err' : HarvestError })],
        [],
      ),
    'updateOfficer' : IDL.Func(
        [OfficerId, IDL.Text],
        [IDL.Variant({ 'ok' : Session, 'err' : AuthError })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };