/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AuthError = { 'notAuthorized' : null } |
  { 'lastAdmin' : null } |
  { 'notFound' : null } |
  { 'invalidCredentials' : null } |
  { 'usernameTaken' : null };
export interface Cell { 'value' : Value, 'name' : string }
export interface CredentialRow {
  'username' : string,
  'displayName' : string,
  'password' : string,
  'role' : Role,
}
export interface Dashboard {
  'stats' : DashboardStats,
  'recent' : Array<HarvestSummary>,
}
export interface DashboardStats {
  'totalValue' : Money,
  'date' : DateText,
  'totalKg' : Kg,
  'farmerCount' : bigint,
  'recordCount' : bigint,
}
export type DateText = string;
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Farmer {
  'id' : FarmerId,
  'code' : string,
  'name' : string,
  'createdAt' : bigint,
  'address' : string,
  'village' : string,
  'notes' : string,
  'phone' : string,
}
export interface FarmerDetail {
  'harvests' : Array<HarvestSummary>,
  'farmer' : Farmer,
}
export type FarmerError = { 'notAuthorized' : null } |
  { 'notFound' : FarmerId } |
  { 'duplicateCode' : string };
export type FarmerId = bigint;
export interface Harvest {
  'id' : HarvestId,
  'kg' : Kg,
  'officerId' : OfficerId,
  'total' : Money,
  'farmerId' : FarmerId,
  'date' : DateText,
  'createdAt' : bigint,
  'officerName' : string,
  'pricePerKg' : Money,
  'farmerCode' : string,
  'farmerName' : string,
  'product' : Product,
}
export type HarvestError = { 'notAuthorized' : null } |
  { 'farmerNotFound' : FarmerId } |
  { 'notFound' : HarvestId };
export type HarvestId = bigint;
export interface HarvestInput {
  'kg' : Kg,
  'farmerId' : FarmerId,
  'date' : DateText,
  'pricePerKg' : Money,
  'product' : Product,
}
export interface HarvestSummary {
  'id' : HarvestId,
  'kg' : Kg,
  'officerId' : OfficerId,
  'total' : Money,
  'date' : DateText,
  'officerName' : string,
  'pricePerKg' : Money,
  'product' : Product,
}
export type Kg = bigint;
export type Money = bigint;
export type OfficerId = bigint;
export interface PriceEntry {
  'pricePerKg' : Money,
  'updatedAt' : bigint,
  'product' : Product,
}
export type PriceError = { 'notAuthorized' : null };
export type Product = { 'mustard' : null } |
  { 'other' : null } |
  { 'pear' : null } |
  { 'banana' : null } |
  { 'passion' : null } |
  { 'woodApple' : null } |
  { 'guava' : null };
export interface Report {
  'to' : DateText,
  'totalValue' : Money,
  'from' : DateText,
  'totalKg' : Kg,
  'kind' : ReportKind,
  'rows' : Array<ReportRow>,
  'recordCount' : bigint,
}
export type ReportError = { 'notAuthorized' : null } |
  { 'invalidRange' : null };
export type ReportKind = { 'byOfficer' : null } |
  { 'byProduct' : null } |
  { 'byFarmer' : null } |
  { 'monthly' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export interface ReportRow {
  'kg' : Kg,
  'key' : string,
  'title' : string,
  'value' : Money,
  'count' : bigint,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Role = { 'admin' : null } |
  { 'officer' : null };
export interface Session {
  'id' : OfficerId,
  'username' : string,
  'displayName' : string,
  'role' : Role,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  /**
   * / Add a farmer (admin only).
   */
  'addFarmer' : ActorMethod<
    [string, string, string, string, string, string],
    { 'ok' : Farmer } |
      { 'err' : FarmerError }
  >,
  /**
   * / Enter a harvest record. The price used is frozen into the record.
   */
  'addHarvest' : ActorMethod<
    [HarvestInput],
    { 'ok' : Harvest } |
      { 'err' : HarvestError }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create an officer account (admin only).
   */
  'createOfficer' : ActorMethod<
    [string, string, string],
    { 'ok' : Session } |
      { 'err' : AuthError }
  >,
  /**
   * / Delete a harvest record (admin only).
   */
  'deleteHarvest' : ActorMethod<
    [HarvestId],
    { 'ok' : null } |
      { 'err' : HarvestError }
  >,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Static Markdown documentation of the backend's public API.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Today's totals plus the latest harvest entries.
   * / Officers are scoped to their own records; admin sees company-wide totals.
   */
  'getDashboard' : ActorMethod<[DateText], Dashboard>,
  /**
   * / Fetch one farmer with that farmer's harvest history.
   */
  'getFarmer' : ActorMethod<[FarmerId], [] | [FarmerDetail]>,
  /**
   * / Harvest history for one farmer.
   */
  'getFarmerHarvests' : ActorMethod<[FarmerId], Array<HarvestSummary>>,
  /**
   * / Fetch one harvest record.
   */
  'getHarvest' : ActorMethod<[HarvestId], [] | [Harvest]>,
  /**
   * / Build a report of the requested kind over a date range.
   * / Officers are scoped to their own records; admin sees all.
   */
  'getReport' : ActorMethod<
    [ReportKind, DateText, DateText],
    { 'ok' : Report } |
      { 'err' : ReportError }
  >,
  /**
   * / The seeded sign-in credentials (admin + six officers) shown on the
   * / pre-login credentials panel. Intentionally public: it returns only the
   * / accounts created by the migration seed (ids 0-6) and no other account data.
   */
  'getSeededCredentials' : ActorMethod<[], Array<CredentialRow>>,
  /**
   * / The signed-in user's session, or `null` when not signed in.
   */
  'getSession' : ActorMethod<[], [] | [Session]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List every farmer.
   */
  'listFarmers' : ActorMethod<[], Array<Farmer>>,
  /**
   * / List harvest records. Officers see only their own; admin sees all.
   */
  'listHarvests' : ActorMethod<[], Array<Harvest>>,
  /**
   * / List all officer accounts (admin only).
   */
  'listOfficers' : ActorMethod<[], Array<Session>>,
  /**
   * / The current price list for all seven products.
   */
  'listPrices' : ActorMethod<[], Array<PriceEntry>>,
  /**
   * / Sign in with username, password and the selected role.
   */
  'login' : ActorMethod<
    [string, string, Role],
    { 'ok' : Session } |
      { 'err' : AuthError }
  >,
  /**
   * / Clear the current session.
   */
  'logout' : ActorMethod<[], undefined>,
  /**
   * / Reset an officer's password (admin only).
   */
  'resetOfficerPassword' : ActorMethod<
    [OfficerId, string],
    { 'ok' : null } |
      { 'err' : AuthError }
  >,
  'schema' : ActorMethod<[], string>,
  /**
   * / Search farmers across code, name, phone and village.
   */
  'searchFarmers' : ActorMethod<[string], Array<Farmer>>,
  /**
   * / Update the current price per kg for one product (admin only).
   */
  'setPrice' : ActorMethod<
    [Product, Money],
    { 'ok' : PriceEntry } |
      { 'err' : PriceError }
  >,
  /**
   * / Edit a farmer's details (admin only).
   */
  'updateFarmer' : ActorMethod<
    [FarmerId, string, string, string, string, string, string],
    { 'ok' : Farmer } |
      { 'err' : FarmerError }
  >,
  /**
   * / Edit a harvest record (admin only).
   */
  'updateHarvest' : ActorMethod<
    [HarvestId, HarvestInput],
    { 'ok' : Harvest } |
      { 'err' : HarvestError }
  >,
  /**
   * / Update an officer's display name (admin only).
   */
  'updateOfficer' : ActorMethod<
    [OfficerId, string],
    { 'ok' : Session } |
      { 'err' : AuthError }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];