/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Cell {
    value: Value;
    name: string;
}
export interface CredentialRow {
    username: string;
    displayName: string;
    password: string;
    role: Role;
}
export interface Dashboard {
    stats: DashboardStats;
    recent: Array<HarvestSummary>;
}
export interface DashboardStats {
    totalValue: Money;
    date: DateText;
    totalKg: Kg;
    farmerCount: bigint;
    recordCount: bigint;
}
export type DateText = string;
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface Farmer {
    id: FarmerId;
    code: string;
    name: string;
    createdAt: bigint;
    address: string;
    village: string;
    notes: string;
    phone: string;
}
export interface FarmerDetail {
    harvests: Array<HarvestSummary>;
    farmer: Farmer;
}
export type FarmerError = {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "notFound";
    notFound: FarmerId;
} | {
    __kind__: "duplicateCode";
    duplicateCode: string;
};
export type FarmerId = bigint;
export interface Harvest {
    id: HarvestId;
    kg: Kg;
    officerId: OfficerId;
    total: Money;
    farmerId: FarmerId;
    date: DateText;
    createdAt: bigint;
    officerName: string;
    pricePerKg: Money;
    farmerCode: string;
    farmerName: string;
    product: Product;
}
export type HarvestError = {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "farmerNotFound";
    farmerNotFound: FarmerId;
} | {
    __kind__: "notFound";
    notFound: HarvestId;
};
export type HarvestId = bigint;
export interface HarvestInput {
    kg: Kg;
    farmerId: FarmerId;
    date: DateText;
    pricePerKg: Money;
    product: Product;
}
export interface HarvestSummary {
    id: HarvestId;
    kg: Kg;
    officerId: OfficerId;
    total: Money;
    date: DateText;
    officerName: string;
    pricePerKg: Money;
    product: Product;
}
export type Kg = bigint;
export type Money = bigint;
export type OfficerId = bigint;
export interface PriceEntry {
    pricePerKg: Money;
    updatedAt: bigint;
    product: Product;
}
export interface Report {
    to: DateText;
    totalValue: Money;
    from: DateText;
    totalKg: Kg;
    kind: ReportKind;
    rows: Array<ReportRow>;
    recordCount: bigint;
}
export interface ReportRow {
    kg: Kg;
    key: string;
    title: string;
    value: Money;
    count: bigint;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface Session {
    id: OfficerId;
    username: string;
    displayName: string;
    role: Role;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum AuthError {
    notAuthorized = "notAuthorized",
    lastAdmin = "lastAdmin",
    notFound = "notFound",
    invalidCredentials = "invalidCredentials",
    usernameTaken = "usernameTaken"
}
export enum PriceError {
    notAuthorized = "notAuthorized"
}
export enum Product {
    mustard = "mustard",
    other = "other",
    pear = "pear",
    banana = "banana",
    passion = "passion",
    woodApple = "woodApple",
    guava = "guava"
}
export enum ReportError {
    notAuthorized = "notAuthorized",
    invalidRange = "invalidRange"
}
export enum ReportKind {
    byOfficer = "byOfficer",
    byProduct = "byProduct",
    byFarmer = "byFarmer",
    monthly = "monthly",
    daily = "daily",
    weekly = "weekly"
}
export enum Role {
    admin = "admin",
    officer = "officer"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    /**
     * / Add a farmer (admin only).
     */
    addFarmer(code: string, name: string, phone: string, village: string, address: string, notes: string): Promise<{
        __kind__: "ok";
        ok: Farmer;
    } | {
        __kind__: "err";
        err: FarmerError;
    }>;
    /**
     * / Enter a harvest record. The price used is frozen into the record.
     */
    addHarvest(input: HarvestInput): Promise<{
        __kind__: "ok";
        ok: Harvest;
    } | {
        __kind__: "err";
        err: HarvestError;
    }>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Create an officer account (admin only).
     */
    createOfficer(username: string, password: string, displayName: string): Promise<{
        __kind__: "ok";
        ok: Session;
    } | {
        __kind__: "err";
        err: AuthError;
    }>;
    /**
     * / Delete a harvest record (admin only).
     */
    deleteHarvest(id: HarvestId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: HarvestError;
    }>;
    execute(qJson: string): Promise<Result>;
    /**
     * / Static Markdown documentation of the backend's public API.
     */
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Today's totals plus the latest harvest entries.
     * / Officers are scoped to their own records; admin sees company-wide totals.
     */
    getDashboard(today: DateText): Promise<Dashboard>;
    /**
     * / Fetch one farmer with that farmer's harvest history.
     */
    getFarmer(id: FarmerId): Promise<FarmerDetail | null>;
    /**
     * / Harvest history for one farmer.
     */
    getFarmerHarvests(farmerId: FarmerId): Promise<Array<HarvestSummary>>;
    /**
     * / Fetch one harvest record.
     */
    getHarvest(id: HarvestId): Promise<Harvest | null>;
    /**
     * / Build a report of the requested kind over a date range.
     * / Officers are scoped to their own records; admin sees all.
     */
    getReport(kind: ReportKind, from: DateText, to: DateText): Promise<{
        __kind__: "ok";
        ok: Report;
    } | {
        __kind__: "err";
        err: ReportError;
    }>;
    /**
     * / The seeded sign-in credentials (admin + six officers) shown on the
     * / pre-login credentials panel. Intentionally public: it returns only the
     * / accounts created by the migration seed (ids 0-6) and no other account data.
     */
    getSeededCredentials(): Promise<Array<CredentialRow>>;
    /**
     * / The signed-in user's session, or `null` when not signed in.
     */
    getSession(): Promise<Session | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / List every farmer.
     */
    listFarmers(): Promise<Array<Farmer>>;
    /**
     * / List harvest records. Officers see only their own; admin sees all.
     */
    listHarvests(): Promise<Array<Harvest>>;
    /**
     * / List all officer accounts (admin only).
     */
    listOfficers(): Promise<Array<Session>>;
    /**
     * / The current price list for all seven products.
     */
    listPrices(): Promise<Array<PriceEntry>>;
    /**
     * / Sign in with username, password and the selected role.
     */
    login(username: string, password: string, role: Role): Promise<{
        __kind__: "ok";
        ok: Session;
    } | {
        __kind__: "err";
        err: AuthError;
    }>;
    /**
     * / Clear the current session.
     */
    logout(): Promise<void>;
    /**
     * / Reset an officer's password (admin only).
     */
    resetOfficerPassword(id: OfficerId, password: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: AuthError;
    }>;
    schema(): Promise<string>;
    /**
     * / Search farmers across code, name, phone and village.
     */
    searchFarmers(term: string): Promise<Array<Farmer>>;
    /**
     * / Update the current price per kg for one product (admin only).
     */
    setPrice(product: Product, pricePerKg: Money): Promise<{
        __kind__: "ok";
        ok: PriceEntry;
    } | {
        __kind__: "err";
        err: PriceError;
    }>;
    /**
     * / Edit a farmer's details (admin only).
     */
    updateFarmer(id: FarmerId, code: string, name: string, phone: string, village: string, address: string, notes: string): Promise<{
        __kind__: "ok";
        ok: Farmer;
    } | {
        __kind__: "err";
        err: FarmerError;
    }>;
    /**
     * / Edit a harvest record (admin only).
     */
    updateHarvest(id: HarvestId, input: HarvestInput): Promise<{
        __kind__: "ok";
        ok: Harvest;
    } | {
        __kind__: "err";
        err: HarvestError;
    }>;
    /**
     * / Update an officer's display name (admin only).
     */
    updateOfficer(id: OfficerId, displayName: string): Promise<{
        __kind__: "ok";
        ok: Session;
    } | {
        __kind__: "err";
        err: AuthError;
    }>;
}
import type { AuthError as _AuthError, Cell as _Cell, CredentialRow as _CredentialRow, Dashboard as _Dashboard, DashboardStats as _DashboardStats, DateText as _DateText, Error as _Error, Farmer as _Farmer, FarmerDetail as _FarmerDetail, FarmerError as _FarmerError, FarmerId as _FarmerId, Harvest as _Harvest, HarvestError as _HarvestError, HarvestId as _HarvestId, HarvestInput as _HarvestInput, HarvestSummary as _HarvestSummary, Kg as _Kg, Money as _Money, OfficerId as _OfficerId, PriceEntry as _PriceEntry, PriceError as _PriceError, Product as _Product, Report as _Report, ReportError as _ReportError, ReportKind as _ReportKind, ReportRow as _ReportRow, Result as _Result, Result__1 as _Result__1, Role as _Role, Session as _Session, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addFarmer(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<{
        __kind__: "ok";
        ok: Farmer;
    } | {
        __kind__: "err";
        err: FarmerError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addFarmer(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFarmer(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addHarvest(arg0: HarvestInput): Promise<{
        __kind__: "ok";
        ok: Harvest;
    } | {
        __kind__: "err";
        err: HarvestError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addHarvest(to_candid_HarvestInput_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHarvest(to_candid_HarvestInput_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createOfficer(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: Session;
    } | {
        __kind__: "err";
        err: AuthError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createOfficer(arg0, arg1, arg2);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOfficer(arg0, arg1, arg2);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteHarvest(arg0: HarvestId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: HarvestError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHarvest(arg0);
                return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHarvest(arg0);
            return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboard(arg0: DateText): Promise<Dashboard> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboard(arg0);
                return from_candid_Dashboard_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboard(arg0);
            return from_candid_Dashboard_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFarmer(arg0: FarmerId): Promise<FarmerDetail | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFarmer(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFarmer(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFarmerHarvests(arg0: FarmerId): Promise<Array<HarvestSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFarmerHarvests(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFarmerHarvests(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHarvest(arg0: HarvestId): Promise<Harvest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHarvest(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHarvest(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReport(arg0: ReportKind, arg1: DateText, arg2: DateText): Promise<{
        __kind__: "ok";
        ok: Report;
    } | {
        __kind__: "err";
        err: ReportError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getReport(to_candid_ReportKind_n42(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_variant_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReport(to_candid_ReportKind_n42(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_variant_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSeededCredentials(): Promise<Array<CredentialRow>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSeededCredentials();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSeededCredentials();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSession(): Promise<Session | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession();
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession();
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listFarmers(): Promise<Array<Farmer>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFarmers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFarmers();
            return result;
        }
    }
    async listHarvests(): Promise<Array<Harvest>> {
        if (this.processError) {
            try {
                const result = await this.actor.listHarvests();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listHarvests();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async listOfficers(): Promise<Array<Session>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOfficers();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOfficers();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPrices(): Promise<Array<PriceEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPrices();
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPrices();
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: string, arg1: string, arg2: Role): Promise<{
        __kind__: "ok";
        ok: Session;
    } | {
        __kind__: "err";
        err: AuthError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1, to_candid_Role_n57(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1, to_candid_Role_n57(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async logout(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logout();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout();
            return result;
        }
    }
    async resetOfficerPassword(arg0: OfficerId, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: AuthError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.resetOfficerPassword(arg0, arg1);
                return from_candid_variant_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetOfficerPassword(arg0, arg1);
            return from_candid_variant_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async searchFarmers(arg0: string): Promise<Array<Farmer>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchFarmers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchFarmers(arg0);
            return result;
        }
    }
    async setPrice(arg0: Product, arg1: Money): Promise<{
        __kind__: "ok";
        ok: PriceEntry;
    } | {
        __kind__: "err";
        err: PriceError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setPrice(to_candid_Product_n10(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_variant_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPrice(to_candid_Product_n10(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_variant_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateFarmer(arg0: FarmerId, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<{
        __kind__: "ok";
        ok: Farmer;
    } | {
        __kind__: "err";
        err: FarmerError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFarmer(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFarmer(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateHarvest(arg0: HarvestId, arg1: HarvestInput): Promise<{
        __kind__: "ok";
        ok: Harvest;
    } | {
        __kind__: "err";
        err: HarvestError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHarvest(arg0, to_candid_HarvestInput_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHarvest(arg0, to_candid_HarvestInput_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOfficer(arg0: OfficerId, arg1: string): Promise<{
        __kind__: "ok";
        ok: Session;
    } | {
        __kind__: "err";
        err: AuthError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOfficer(arg0, arg1);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOfficer(arg0, arg1);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AuthError_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthError): AuthError {
    return "notAuthorized" in value ? AuthError.notAuthorized : "lastAdmin" in value ? AuthError.lastAdmin : "notFound" in value ? AuthError.notFound : "invalidCredentials" in value ? AuthError.invalidCredentials : "usernameTaken" in value ? AuthError.usernameTaken : value;
}
function from_candid_Cell_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_CredentialRow_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CredentialRow): CredentialRow {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_Dashboard_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Dashboard): Dashboard {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_FarmerDetail_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FarmerDetail): FarmerDetail {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_FarmerError_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FarmerError): FarmerError {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_HarvestError_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HarvestError): HarvestError {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_HarvestSummary_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HarvestSummary): HarvestSummary {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Harvest_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Harvest): Harvest {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PriceEntry_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriceEntry): PriceEntry {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_PriceError_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriceError): PriceError {
    return "notAuthorized" in value ? PriceError.notAuthorized : value;
}
function from_candid_Product_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return "mustard" in value ? Product.mustard : "other" in value ? Product.other : "pear" in value ? Product.pear : "banana" in value ? Product.banana : "passion" in value ? Product.passion : "woodApple" in value ? Product.woodApple : "guava" in value ? Product.guava : value;
}
function from_candid_ReportError_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportError): ReportError {
    return "notAuthorized" in value ? ReportError.notAuthorized : "invalidRange" in value ? ReportError.invalidRange : value;
}
function from_candid_ReportKind_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportKind): ReportKind {
    return "byOfficer" in value ? ReportKind.byOfficer : "byProduct" in value ? ReportKind.byProduct : "byFarmer" in value ? ReportKind.byFarmer : "monthly" in value ? ReportKind.monthly : "daily" in value ? ReportKind.daily : "weekly" in value ? ReportKind.weekly : value;
}
function from_candid_Report_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Report): Report {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return "admin" in value ? Role.admin : "officer" in value ? Role.officer : value;
}
function from_candid_Session_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Session): Session {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FarmerDetail]): FarmerDetail | null {
    return value.length === 0 ? null : from_candid_FarmerDetail_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Harvest]): Harvest | null {
    return value.length === 0 ? null : from_candid_Harvest_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Session]): Session | null {
    return value.length === 0 ? null : from_candid_Session_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _HarvestId;
    kg: _Kg;
    officerId: _OfficerId;
    total: _Money;
    farmerId: _FarmerId;
    date: _DateText;
    createdAt: bigint;
    officerName: string;
    pricePerKg: _Money;
    farmerCode: string;
    farmerName: string;
    product: _Product;
}): {
    id: HarvestId;
    kg: Kg;
    officerId: OfficerId;
    total: Money;
    farmerId: FarmerId;
    date: DateText;
    createdAt: bigint;
    officerName: string;
    pricePerKg: Money;
    farmerCode: string;
    farmerName: string;
    product: Product;
} {
    return {
        id: value.id,
        kg: value.kg,
        officerId: value.officerId,
        total: value.total,
        farmerId: value.farmerId,
        date: value.date,
        createdAt: value.createdAt,
        officerName: value.officerName,
        pricePerKg: value.pricePerKg,
        farmerCode: value.farmerCode,
        farmerName: value.farmerName,
        product: from_candid_Product_n14(_uploadFile, _downloadFile, value.product)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OfficerId;
    username: string;
    displayName: string;
    role: _Role;
}): {
    id: OfficerId;
    username: string;
    displayName: string;
    role: Role;
} {
    return {
        id: value.id,
        username: value.username,
        displayName: value.displayName,
        role: from_candid_Role_n21(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n26(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n30(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stats: _DashboardStats;
    recent: Array<_HarvestSummary>;
}): {
    stats: DashboardStats;
    recent: Array<HarvestSummary>;
} {
    return {
        stats: value.stats,
        recent: from_candid_vec_n35(_uploadFile, _downloadFile, value.recent)
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _HarvestId;
    kg: _Kg;
    officerId: _OfficerId;
    total: _Money;
    date: _DateText;
    officerName: string;
    pricePerKg: _Money;
    product: _Product;
}): {
    id: HarvestId;
    kg: Kg;
    officerId: OfficerId;
    total: Money;
    date: DateText;
    officerName: string;
    pricePerKg: Money;
    product: Product;
} {
    return {
        id: value.id,
        kg: value.kg,
        officerId: value.officerId,
        total: value.total,
        date: value.date,
        officerName: value.officerName,
        pricePerKg: value.pricePerKg,
        product: from_candid_Product_n14(_uploadFile, _downloadFile, value.product)
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    harvests: Array<_HarvestSummary>;
    farmer: _Farmer;
}): {
    harvests: Array<HarvestSummary>;
    farmer: Farmer;
} {
    return {
        harvests: from_candid_vec_n35(_uploadFile, _downloadFile, value.harvests),
        farmer: value.farmer
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    to: _DateText;
    totalValue: _Money;
    from: _DateText;
    totalKg: _Kg;
    kind: _ReportKind;
    rows: Array<_ReportRow>;
    recordCount: bigint;
}): {
    to: DateText;
    totalValue: Money;
    from: DateText;
    totalKg: Kg;
    kind: ReportKind;
    rows: Array<ReportRow>;
    recordCount: bigint;
} {
    return {
        to: value.to,
        totalValue: value.totalValue,
        from: value.from,
        totalKg: value.totalKg,
        kind: from_candid_ReportKind_n46(_uploadFile, _downloadFile, value.kind),
        rows: value.rows,
        recordCount: value.recordCount
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    displayName: string;
    password: string;
    role: _Role;
}): {
    username: string;
    displayName: string;
    password: string;
    role: Role;
} {
    return {
        username: value.username,
        displayName: value.displayName,
        password: value.password,
        role: from_candid_Role_n21(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pricePerKg: _Money;
    updatedAt: bigint;
    product: _Product;
}): {
    pricePerKg: Money;
    updatedAt: bigint;
    product: Product;
} {
    return {
        pricePerKg: value.pricePerKg,
        updatedAt: value.updatedAt,
        product: from_candid_Product_n14(_uploadFile, _downloadFile, value.product)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Harvest;
} | {
    err: _HarvestError;
}): {
    __kind__: "ok";
    ok: Harvest;
} | {
    __kind__: "err";
    err: HarvestError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Harvest_n12(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_HarvestError_n15(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notAuthorized: null;
} | {
    farmerNotFound: _FarmerId;
} | {
    notFound: _HarvestId;
}): {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "farmerNotFound";
    farmerNotFound: FarmerId;
} | {
    __kind__: "notFound";
    notFound: HarvestId;
} {
    return "notAuthorized" in value ? {
        __kind__: "notAuthorized",
        notAuthorized: value.notAuthorized
    } : "farmerNotFound" in value ? {
        __kind__: "farmerNotFound",
        farmerNotFound: value.farmerNotFound
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Session;
} | {
    err: _AuthError;
}): {
    __kind__: "ok";
    ok: Session;
} | {
    __kind__: "err";
    err: AuthError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Session_n19(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AuthError_n22(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _HarvestError;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: HarvestError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_HarvestError_n15(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Report;
} | {
    err: _ReportError;
}): {
    __kind__: "ok";
    ok: Report;
} | {
    __kind__: "err";
    err: ReportError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Report_n44(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_ReportError_n47(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Farmer;
} | {
    err: _FarmerError;
}): {
    __kind__: "ok";
    ok: Farmer;
} | {
    __kind__: "err";
    err: FarmerError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_FarmerError_n6(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _AuthError;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: AuthError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AuthError_n22(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PriceEntry;
} | {
    err: _PriceError;
}): {
    __kind__: "ok";
    ok: PriceEntry;
} | {
    __kind__: "err";
    err: PriceError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_PriceEntry_n55(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_PriceError_n60(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notAuthorized: null;
} | {
    notFound: _FarmerId;
} | {
    duplicateCode: string;
}): {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "notFound";
    notFound: FarmerId;
} | {
    __kind__: "duplicateCode";
    duplicateCode: string;
} {
    return "notAuthorized" in value ? {
        __kind__: "notAuthorized",
        notAuthorized: value.notAuthorized
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "duplicateCode" in value ? {
        __kind__: "duplicateCode",
        duplicateCode: value.duplicateCode
    } : value;
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HarvestSummary>): Array<HarvestSummary> {
    return value.map((x)=>from_candid_HarvestSummary_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CredentialRow>): Array<CredentialRow> {
    return value.map((x)=>from_candid_CredentialRow_n49(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Harvest>): Array<Harvest> {
    return value.map((x)=>from_candid_Harvest_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Session>): Array<Session> {
    return value.map((x)=>from_candid_Session_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PriceEntry>): Array<PriceEntry> {
    return value.map((x)=>from_candid_PriceEntry_n55(_uploadFile, _downloadFile, x));
}
function to_candid_HarvestInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HarvestInput): _HarvestInput {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Product_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): _Product {
    return value == Product.mustard ? {
        mustard: null
    } : value == Product.other ? {
        other: null
    } : value == Product.pear ? {
        pear: null
    } : value == Product.banana ? {
        banana: null
    } : value == Product.passion ? {
        passion: null
    } : value == Product.woodApple ? {
        woodApple: null
    } : value == Product.guava ? {
        guava: null
    } : value;
}
function to_candid_ReportKind_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportKind): _ReportKind {
    return value == ReportKind.byOfficer ? {
        byOfficer: null
    } : value == ReportKind.byProduct ? {
        byProduct: null
    } : value == ReportKind.byFarmer ? {
        byFarmer: null
    } : value == ReportKind.monthly ? {
        monthly: null
    } : value == ReportKind.daily ? {
        daily: null
    } : value == ReportKind.weekly ? {
        weekly: null
    } : value;
}
function to_candid_Role_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return value == Role.admin ? {
        admin: null
    } : value == Role.officer ? {
        officer: null
    } : value;
}
function to_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kg: Kg;
    farmerId: FarmerId;
    date: DateText;
    pricePerKg: Money;
    product: Product;
}): {
    kg: _Kg;
    farmerId: _FarmerId;
    date: _DateText;
    pricePerKg: _Money;
    product: _Product;
} {
    return {
        kg: value.kg,
        farmerId: value.farmerId,
        date: value.date,
        pricePerKg: value.pricePerKg,
        product: to_candid_Product_n10(_uploadFile, _downloadFile, value.product)
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
